spring.datasource.url=jdbc:mysql://localhost:3306/latiendadekelly?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
app.security.admin-token=dev-admin-token
